<?php
/**
 * Created by PhpStorm.
 * User: JHR
 * Date: 2019/4/18
 * Time: 18:17
 */
namespace app\admin\controller;
use think\Controller;
use my\Auth;
class Base extends Controller {

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function getAllowList() {
        $allow = [
            ''
        ];
    }

}